config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :companies
  resources :users

  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  else
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
  attr_accessor :email, :password
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, 
            :last_name,
            :email,
            :phone,
            :city,
            :town, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    id = params[:id]
    @company = Company.find(id)
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if (@company.save)
      redirect_to companies_path, notice: 'Company successful created'
    else
      flash[:error] = 'Company has errors' 
      render 'new'
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to companies_path, notice: 'User successfully updated'
    else
      flash[:error] = "Couldn't update company"
      render :edit
    end    
  end    

  def destroy
    id = params[:id]
    company = Company.find(id)
    company.destroy
    redirect_to company_path, notice: "L'entreprise #{company.name} avec l'email #{company.email} a été supprimé"
  end

  private
  def company_params
    params.require(:company).permit(:name, :email)
  end
end

app/controllers/sessions_controller.rb
class SessionController < ApplicationController
  
  def new
  end

  def create
    email = params[:email]
    password = params[:password]
    user = User.find_by(email: email)&.authenticate(password)
    if user
      session[:current_user] = user
      redirect_to users_path, notice: 'Successfully logged in'
    else
      redirect_to login_path, alert: 'email or password incorrect'
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to login_path, notice: 'Successfully logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    id = params[:id]
    @user = User.find(id)
  end

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: 'Your account was successfully created'
    else
      flash[:error] = "User has errors"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path, notice: 'User was successfully updated'
    else
      flash[:error] = "User has errors"
      render 'edit'
    end
  end

  def destroy
    id = params[:id]
    user = User.find(id)
    user.destroy
    redirect_to users_path, notice: 'User was successfully deleted'
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone, :city, :town, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<%= form_with model: company do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>  
  <%= form.submit 'register company' %>
<% end %>

app/views/companies/create.html.erb
<h1>Companies#create</h1>
<p>Find me in app/views/companies/create.html.erb</p>

app/views/companies/destroy.html.erb
<h1>Companies#destroy</h1>
<p>Find me in app/views/companies/destroy.html.erb</p>

app/views/companies/edit.html.erb
<h1>Companies#edit</h1>


<%= form_with model: @company do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>  

  <%= form.submit 'Update company' %>
<% end %>

app/views/companies/index.html.erb
<h1>Companies#index</h1>

<table class="">
  <thead>
    <tr>
      <th>name</th>
      <th>email</th>      
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>        
        <td><%= company.email %></td>
        <td><%= link_to 'show', company_path(company) %></td>
        <td><%= link_to "edit", edit_company_path(company) %></td>
         <td><%= link_to "delete", company_path(company), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer?" } %></td>
      </tr>
    <% end %>
  </tbody>
<table>

app/views/companies/new.html.erb
<h1>Companies#new</h1>
<p>Find me in app/views/companies/new.html.erb</p>

<%= render partial: 'form', locals: {company: @company}%>

app/views/companies/show.html.erb
<h1>Companies#show</h1>

<h2>Fiche entreprise</h2>
<ul>
    <li>
    <span>Nom de l'entreprise: </span> 
    <%= @company.name %>
    </li>

    <li>
    <span>Email: </span> 
    <%= @company.email %>
    </li>
</ul>
 
             
       

app/views/companies/update.html.erb
<h1>Companies#update</h1>
<p>Find me in app/views/companies/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AttendanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: user do |form|%>
  <div>
    <%= form.label :first_name, 'First Name' %>
    <%= form.text_field :first_name %>
    <% if user.errors[:first_name] %>
      <span style='color: red'><%= user.errors[:first_name][0] %></span>
    <% end %>
  </div>
  <div>
    <%= form.label :last_name, 'Last Name' %>
    <%= form.text_field :last_name %>
  </div>
  <% if user.errors[:last_name] %>
    <span style='color: red'><%= user.errors[:last_name][0] %></span>
  <% end %>
  <div>
    <%= form.label :email, 'Email' %>
    <%= form.text_field :email %>
  </div>
  <% if user.errors[:email] %>
    <span style='color: red'><%= user.errors[:email][0] %></span>
  <% end %>
  <div>
    <%= form.label :phone, 'Phone' %>
    <%= form.text_field :phone %>
  </div>
  <% if user.errors[:phone] %>
    <span style='color: red'><%= user.errors[:phone][0] %></span>
  <% end %>
  <div>
    <%= form.label :city, 'City' %>
    <%= form.text_field :city %>
  </div>
  <% if user.errors[:city] %>
    <span style='color: red'><%= user.errors[:city][0] %></span>
  <% end %>
  <div>
    <%= form.label :town, 'Town' %>
    <%= form.text_field :town %>
  </div>
  <% if user.errors[:town] %>
    <span style='color: red'><%= user.errors[:town][0] %></span>
  <% end %>
  <div>
    <%= form.label :password, 'Password' %>
    <%= form.password_field :password %>
  </div>
  <% if user.errors[:password] %>
    <span style='color: red'><%= user.errors[:password][0] %></span>
  <% end %>
  <div>
    <%= form.label :password_confirmation, 'Password Confirmation' %>
    <%= form.password_field :password_confirmation %>
  </div>
  <% if user.errors[:password_confirmation] %>
    <span style='color: red'><%= user.errors[:password_confirmation][0] %></span>
  <% end %>
  <% if user.persisted? %>
    <%= form.submit 'Update user' %>
  <% else %>
    <%= form.submit 'Create account' %>
  <% end %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>User Modification</h1>
<%= render partial: 'form', locals: {user: @user}%>

app/views/users/index.html.erb
<div>
  <button>
    <%= link_to 'Add a user', new_user_path%>
  </button>
</div>
<table>
  <thead>
    <tr>
      <th>first name</th>
      <th>last name</th>
      <th>email</th>
      <th>phone</th>
      <th>city</th>
      <th>town</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.phone %></td>
      <td><%= user.city %></td>
      <td><%= user.town %></td>
      <td><%= link_to 'show', user_path(user)%></td>
      <td><%= link_to 'edit', edit_user_path(user)%></td>
      <td><%= link_to 'delete', user_path(user), method: :delete, data: {confirm: 'Are you sure?'}%></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Create an account</h1>
<%= render partial: 'form', locals: {user: @user}%>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>
<ul>
  <li>
    <span>email: </span>
    <span><%= @user.email %></span>
  </li>
  <li>
    <span>phone: </span>
    <span><%= @user.phone %></span>
  </li>
  <li>
    <span>city: </span>
    <span><%= @user.city %></span>
  </li>
  <li>
    <span>town: </span>
    <span><%= @user.town %></span>
  </li>
</ul>
<%= link_to 'Back', :back %>
<%= link_to 'Users', users_path 

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>